import "./globals.css";
import type { Metadata } from "next";
import Navbar from "./components/Navbar";
import { Providers } from "./components/Providers";

export const metadata: Metadata = {
  title: "id-dev blog",
  description: "Generated by create next app",
  // icons: {
  //   icon: ["/favicon.ico?v=4"],
  //   apple: ["/apple-touch-icon.png?v=4"],
  //   shortcut: ["/apple-touch-icon.png"],
  // },
  // manifest: "/site.webmanifest",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head></head>
      <body className="bg-white text-black dark:bg-black  dark:selection:bg-black dark:text-white h-full selection:bg-gray-50">
        <Providers>
          <Navbar />
          <main className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 selection:">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
